# Generated by Django 5.0.3 on 2024-04-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=80)),
                ('senha', models.CharField(max_length=80)),
            ],
        ),
    ]
