# Generated by Django 5.0.3 on 2024-04-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default=2308912, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
