# Generated by Django 5.0.3 on 2024-04-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_usuario_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.CharField(default=425, max_length=90),
            preserve_default=False,
        ),
    ]
